### ISSUE TITLE
Add support for SALS mechanisms SCRAM SHA 256 and 512

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-canary#130]
Currently, the canary supports only PLAIN as SASL mechanism for authentication.
We should add SCRAM-SHA 256 and 512 as well, as supported by the underlying used Sarama library.

**Comment by Neustradamus** [comment]
@ppatierno: Thanks a lot for all about SCRAM.
- https://github.com/strimzi/strimzi-canary/pull/131
- https://github.com/strimzi/strimzi-canary/pull/155

Please rename the title -> SASL ;)

Linked to:
- https://github.com/scram-xmpp/info/issues/1
