### ISSUE TITLE
Error processing consumed records percentage: No data samples available in the time window ring

### ISSUE THREAD

**Issue by jcmonsalve2021** [strimzi/strimzi-canary#172]
Hello, I have these error messages, but I don't know why, when we check the status of the cluster, everything is fine.

I0330 15:24:34.493776       1 main.go:48] Starting Strimzi canary tool [0.2.0] with config: {BootstrapServers:[xxxxxx.svc.cluster.local:9092], BootstrapBackoffMaxAttempts:10, BootstrapBackoffScale:5000, Topic:__strimzi_canary, TopicConfig:map[], ReconcileInterval:30000 ms, ClientID:strimzi-canary-client, ConsumerGroupID:strimzi-canary-group, ProducerLatencyBuckets:[100 200 400 800 1600], EndToEndLatencyBuckets:[100 200 400 800 1600], ExpectedClusterSize:-1, KafkaVersion:2.8.0,SaramaLogEnabled:false, VerbosityLogLevel:0, TLSEnabled:false, TLSCACert:, TLSClientCert:, TLSClientKey:, TLSInsecureSkipVerify:false,SASLMechanism:SCRAM-SHA-512, SASLUser:, SASLPassword:, ConnectionCheckInterval:120000 ms, ConnectionCheckLatencyBuckets:[100 200 400 800 1600], StatusCheckInterval:30000 ms, StatusTimeWindow:300000 ms}
I0330 15:24:34.494192       1 http_server.go:41] Starting HTTP server
I0330 15:24:34.703614       1 canary_manager.go:58] Starting canary manager
I0330 15:24:34.703678       1 connection_check.go:116] Creating Sarama cluster admin
I0330 15:24:35.789413       1 topic.go:116] Creating Sarama cluster admin
I0330 15:24:36.103170       1 topic.go:188] Going to reassign topic partitions if needed
E0330 15:26:22.502116       1 status_check.go:102] Error processing consumed records percentage: No data samples available in the time window ring
E0330 15:26:38.772162       1 status_check.go:102] Error processing consumed records percentage: No data samples available in the time window ring
E0330 15:26:57.609644       1 status_check.go:102] Error processing consumed records percentage: No data samples available in the time window ring
E0330 15:27:20.525477       1 status_check.go:102] Error processing consumed records percentage: No data samples available in the time window ring

**Comment by jcmonsalve2021** [comment]
We found root cause , the topic __strimzi_canary was  in Out of sync replicas for some minutes

**Comment by ppatierno** [comment]
@jcmonsalve2021 can we close this one then?

**Comment by ppatierno** [comment]
No further feedback, going to close this. Feel free to re-open if it's still in place.
