### ISSUE TITLE
Error-related Metrics starting from 0

### ISSUE THREAD

**Issue by leewoobin789** [strimzi/strimzi-canary#215]
**Description**: Error related metrics starting from 0 instead of instantiating it when it first occurs.
**Reason**: After deployment, building an alert rules based on increase of these metrics is challenging, as the error metrics are only instantiated under the circumstance of error precedence in the past. After restarting the pod, the problem repeats again.
**Solution Proposal**: Starting from 0 right after deployment.

Thank you in advance

**Comment by ppatierno** [comment]
Hey @leewoobin789 sorry but I can't understand what you are describing, could you make an actual example please?

**Comment by leewoobin789** [comment]
hi @ppatierno 
When I create a prometheus alert rule of "round(increase(strimzi_canary_topic_alter_assignments_error_total[5m]), 1) > 0", it won't trigger the alert due to the fact that "increase" function of PromQL does not correctly compare the difference between current and previous values, when there isn't any previous value. therefore even if error occurred, the first alert won't be generated as its value is 0.
if all error-related metrics are initiated from beginning on (instead of later in runtime) with 0, it would correctly detect the increased values in it.

**Comment by ppatierno** [comment]
I am not a Prometheus and PromQL expert but isn't it possible to define some default for the `increase` function? 
Or could using a Promtheus rule returning 0 or the increase function help here?
Of course we could even initialize the metric at 0, are you willing to contribute to the project and opening a PR for that?

**Comment by leewoobin789** [comment]
@ppatierno As far as I know, there isn't workaround for this.
i am btw. willing to contribute :) I will send a PR asap if it is ok for you.

**Comment by k-wall** [comment]
Oh. Interesting. I wasn't aware of this problem before. I agree with @leewoobin789, the canary's behaviour is wrong.

The prometheus [docs](https://prometheus.io/docs/instrumenting/writing_clientlibs/#counter) state that "Counters MUST start at 0.". The prometheus client library can't predict the set of the labels that the canary is going to use, so it seems reasonable that the canary itself has to cause the 0 value to be recorded.

I found this blog post informative: https://www.section.io/blog/beware-prometheus-counters-that-do-not-begin-at-zero/

**Comment by leewoobin789** [comment]
I close this issue because it should be solved by the next version.

**Comment by leewoobin789** [comment]
I close this issue because it should be solved by the next version.
