### ISSUE TITLE
Adding proper error handling

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-canary#5]
Currently, with most of the error, the canary tool just panics leaving the application to exit.
We should think about adding proper error handling where it makes sense, trying a retry or recovery logic, or even just exiting.

**Comment by k-wall** [comment]
+1 with the idea of retry, but we need to make sure that an SRE observing the metrics have sufficient metrics to know that the canary is in trouble.  I'd suggest a monotomicly increasing error count metric.

**Comment by ppatierno** [comment]
I totally agree with this, having an error metric with one or more labels specifying the kind of error. But do you agree that it can be addressed working on #5? It's more a wider problem than just this issue.
Maybe you can add this comment on #5 so that we can track the idea about a corresponding metric?
