### ISSUE TITLE
Add TLS support

### ISSUE THREAD

**Issue by robshelly** [strimzi/strimzi-canary#9]
Add TLS support to the canary. Currently the canary config contains an environment variable to enable TLS. However it is disabled by default and not implemented even if enabled.

**Comment by ppatierno** [comment]
To be precise, this issue is about:

* enabling TLS connection to a Kafka cluster (providing a CA certificate to the canary)
* enabling TLS mutual authentication (providing client cert and key to the canary for authentication)
